---
title: "Mathematical symbols and expressions in rmarkdown"
author: "Wenbo Lv"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      dpi = 600,
                      warning = FALSE,
                      message = FALSE,
                      out.width = "100%",
                      out.height = "100%",
                      fig.align = 'center',
                      comment = "##",
                      htmltools.dir.version = FALSE)
```

## 希腊字母

```
| No.  | Lowercase  | Uppercase  |  English  |              IPA              |
| :--: | :--------: | :--------: | :-------: | :---------------------------: |
| $1$  |  $\alpha$  |    $A$     |  $alpha$  |          **/'ælfə/**          |
| $2$  |  $\beta$   |    $B$     |  $beta$   |    **/'bi:tə/or/'beɪtə/**     |
| $3$  |  $\gamma$  |  $\Gamma$  |  $gamma$  |          **/'gæmə/**          |
| $4$  |  $\delta$  |  $\Delta$  |  $delta$  |         **/'deltə/**          |
| $5$  | $\epsilon$ |    $E$     | $epsilon$ |        **/'epsɪlɒn/**         |
| $6$  |  $\zeta$   |    $Z$     |  $zeta$   |         **/'zi:tə/**          |
| $7$  |   $\eta$   |    $H$     |   $eta$   |          **/'i:tə/**          |
| $8$  |  $\theta$  |  $\Theta$  |  $theta$  |         **/'θi:tə/**          |
| $9$  |  $\iota$   |    $I$     |  $iota$   |         **/aɪ'əʊtə/**         |
| $10$ |  $\kappa$  |    $K$     |  $kappa$  |          **/'kæpə/**          |
| $11$ | $\lambda$  | $\lambda$  | $lambda$  |         **/'læmdə/**          |
| $12$ |   $\mu$    |    $M$     |   $mu$    |          **/mju:/**           |
| $13$ |   $\nu$    |    $N$     |   $nu$    |          **/nju:/**           |
| $14$ |   $\xi$    |   $\Xi$    |   $xi$    |   **/ksi/or/'zaɪ/or/'ksaɪ/**  |
| $15$ | $\omicron$ |    $O$     | $omicron$ | **/əu'maikrən/or/'ɑmɪ,krɑn/** |
| $16$ |   $\pi$    |   $\Pi$    |   $pi$    |           **/paɪ/**           |
| $17$ |   $\rho$   |    $P$     |   $rho$   |           **/rəʊ/**           |
| $18$ |  $\sigma$  |  $\Sigma$  |  $sigma$  |         **/'sɪɡmə/**          |
| $19$ |   $\tau$   |    $T$     |   $tau$   |       **/tɔ:/or/taʊ/**        |
| $20$ | $\upsilon$ | $\Upsilon$ | $upsilon$ |  **/'ipsilon/or/'ʌpsilɒn/**   |
| $21$ |   $\phi$   |   $\Phi$   |   $phi$   |           **/faɪ/**           |
| $22$ |   $\chi$   |    $X$     |   $chi$   |           **/kaɪ/**           |
| $23$ |   $\psi$   |   $\Psi$   |   $psi$   |          **/psaɪ/**           |
| $24$ |  $\omega$  |  $\Omega$  |  $omega$  |   **/'əʊmɪɡə/or/oʊ'meɡə/**    |
```
| No.  | Lowercase  | Uppercase  |  English  |              IPA              |
| :--: | :--------: | :--------: | :-------: | :---------------------------: |
| $1$  |  $\alpha$  |    $A$     |  $alpha$  |          **/'ælfə/**          |
| $2$  |  $\beta$   |    $B$     |  $beta$   |    **/'bi:tə/or/'beɪtə/**     |
| $3$  |  $\gamma$  |  $\Gamma$  |  $gamma$  |          **/'gæmə/**          |
| $4$  |  $\delta$  |  $\Delta$  |  $delta$  |         **/'deltə/**          |
| $5$  | $\epsilon$ |    $E$     | $epsilon$ |        **/'epsɪlɒn/**         |
| $6$  |  $\zeta$   |    $Z$     |  $zeta$   |         **/'zi:tə/**          |
| $7$  |   $\eta$   |    $H$     |   $eta$   |          **/'i:tə/**          |
| $8$  |  $\theta$  |  $\Theta$  |  $theta$  |         **/'θi:tə/**          |
| $9$  |  $\iota$   |    $I$     |  $iota$   |         **/aɪ'əʊtə/**         |
| $10$ |  $\kappa$  |    $K$     |  $kappa$  |          **/'kæpə/**          |
| $11$ | $\lambda$  | $\lambda$  | $lambda$  |         **/'læmdə/**          |
| $12$ |   $\mu$    |    $M$     |   $mu$    |          **/mju:/**           |
| $13$ |   $\nu$    |    $N$     |   $nu$    |          **/nju:/**           |
| $14$ |   $\xi$    |   $\Xi$    |   $xi$    |   **/ksi/or/'zaɪ/or/'ksaɪ/**  |
| $15$ | $\omicron$ |    $O$     | $omicron$ | **/əu'maikrən/or/'ɑmɪ,krɑn/** |
| $16$ |   $\pi$    |   $\Pi$    |   $pi$    |           **/paɪ/**           |
| $17$ |   $\rho$   |    $P$     |   $rho$   |           **/rəʊ/**           |
| $18$ |  $\sigma$  |  $\Sigma$  |  $sigma$  |         **/'sɪɡmə/**          |
| $19$ |   $\tau$   |    $T$     |   $tau$   |       **/tɔ:/or/taʊ/**        |
| $20$ | $\upsilon$ | $\Upsilon$ | $upsilon$ |  **/'ipsilon/or/'ʌpsilɒn/**   |
| $21$ |   $\phi$   |   $\Phi$   |   $phi$   |           **/faɪ/**           |
| $22$ |   $\chi$   |    $X$     |   $chi$   |           **/kaɪ/**           |
| $23$ |   $\psi$   |   $\Psi$   |   $psi$   |          **/psaɪ/**           |
| $24$ |  $\omega$  |  $\Omega$  |  $omega$  |   **/'əʊmɪɡə/or/oʊ'meɡə/**    |

## 特殊数学符号

```
|    类型    |   书写方式   |
|:----------:|:------------:|
| 垂直 | $\perp$ |
| 乘以 | $\times$ |
| 除以 | $\div$ |
| 不等于 | $\neq$ |
| 大于等于 | $\geq$ |
| 小于等于 | $\leq$ |
| 约等于 | $\approx$ |
| 恒等于 | $\equiv$ |
| 正比于 | $\propto$ |
| 等价于 | $=:$ |
| 正负 | $\pm$ |
| 负正 | $\mp$ |
| 相似 | $\sim$ |
| 任意 | $\forall$ |
| 存在 | $\exists$ |
| 不存在 | $\nexists$ |
| 属于 | $\in$ |
| 不属于 | $\notin$ |
| 包含 | $\supset$ |
| 真包含 | $\supsetneqq$ |
| 包含于 | $\subset$ |
| 真包含于 | $\subsetneqq$ |
| 不包含于 | $\not\subset$ |
| 并集 | $\cup$ |
| 交集 | $\cap$ |
| 空集 | $\emptyset$ |
| 实数集 | $\mathbb{R}$ |
| 表示集合的大括号 | $\{ ... \}$ |
| 集合并运算符号 | $\mid$ |
| 集合减运算符号 | $\setminus$ |
| 逻辑或运算符号 | $\vee$ |
| 逻辑与运算符号 | $\wedge$ |
| 几何图形相似 | $\simeq$ |
| 几何图形全等 | $\cong$ |
| 无穷大 | $\infty$ |
| 省略号 | $\ldots$ |
| 因为 | $\because$ |
| 所以 | $\therefore$ |
| 角度 | $\angle$ |
| 偏导 | $\partial$ |
| 积分符号 | $\int$ |
| 二重积分 | $\iint$ |
| 三重积分 | $\iiint$ |
| n重积分 | $\idotsint$ |
| 曲线曲面积分 | $\oint$ |
| 求和符号 | $\sum$ |
| 求积符号 | $\prod$ |
| 极限符号 | $lim$ |
| 对n开根号 | $\sqrt{n}$ |
| 自然对数 | $\ln x$ |
| 常用对数 | $\lg x$ |
| 以a为底的对数 | $log_{a}{x}$ |
| 以e为底的指数 | $e^x$ |
| 大N | $\mathcal{N}$ |
| 上标 |  ${a}^{2}$  |
| 下标 |  ${a}_{2}$  |
| 向量 | $\vec{a}$ |
| 平均值 | $\overline{a}$ |
| 拟合值 |  $\widehat{a}$  |
| 一阶导数 |  $\dot{a}$  |
| 二阶导数 | $\ddot{a}$ |
| 模运算/向量加法 | $\oplus$ |
| 张量积/笛卡尔积 | $\otimes$ |
| 六角星(六芒星)上标 | $x^{\ast}$ |
| 五角星上标 | $x^{\star}$ |
| 方块 |  $\square$  |
| 黑填充方块 | $\blacksquare$ |
| 三角 |  $\triangle$  |
| 黑填充三角 | $\blacktriangle$ |
| 1度 | $1^\circ$ |
| 1分 |  $1^\prime$  |
| 1秒 | $1^{\prime\prime}$ |
| 左单箭头 | $\leftarrow$ |
| 右单箭头 | $\rightarrow$ |
| 左双箭头 | $\Leftarrow$ |
| 右双箭头 | $\Rightarrow$ |
| 左右单箭头 | $\leftrightarrow$ |
| 左右双箭头 | $\Leftrightarrow$ |
| ^帽子命令 | $\hat{a}$	 |
| ~帽子命令 | $\tilde{a}$	 |
| 倒尖帽子命令 | $\check{a}$ |
| 4声调帽子命令 | $\grave{a}$ |
| 2声调帽子命令 | $\acute{a}$ |
| 大^帽子命令 | $\widehat{abcdefg}$ |
| 大~帽子命令 | $\widetilde{abcdefg}$ |
```

|  类型  |  书写方式  |
|:------:|:-----------:|
| 垂直 | $\perp$ |
| 乘以 | $\times$ |
| 除以 | $\div$ |
| 不等于 | $\neq$ |
| 大于等于 | $\geq$ |
| 小于等于 | $\leq$ |
| 约等于 | $\approx$ |
| 恒等于 | $\equiv$ |
| 正比于 | $\propto$ |
| 等价于 | $=:$ |
| 正负 | $\pm$ |
| 负正 | $\mp$ |
| 相似 | $\sim$ |
| 任意 | $\forall$ |
| 存在 | $\exists$ |
| 不存在 | $\nexists$ |
| 属于 | $\in$ |
| 不属于 | $\notin$ |
| 包含 | $\supset$ |
| 真包含 | $\supsetneqq$ |
| 包含于 | $\subset$ |
| 真包含于 | $\subsetneqq$ |
| 不包含于 | $\not\subset$ |
| 并集 | $\cup$ |
| 交集 | $\cap$ |
| 空集 | $\emptyset$ |
| 实数集 | $\mathbb{R}$ |
| 表示集合的大括号 | $\{ ... \}$ |
| 集合并运算符号 | $\mid$ |
| 集合减运算符号 | $\setminus$ |
| 逻辑或运算符号 | $\vee$ |
| 逻辑与运算符号 | $\wedge$ |
| 几何图形相似 | $\simeq$ |
| 几何图形全等 | $\cong$ |
| 无穷大 | $\infty$ |
| 省略号 | $\ldots$ |
| 因为 | $\because$ |
| 所以 | $\therefore$ |
| 角度 | $\angle$ |
| 偏导 | $\partial$ |
| 积分符号 | $\int$ |
| 二重积分 | $\iint$ |
| 三重积分 | $\iiint$ |
| n重积分 | $\idotsint$ |
| 曲线曲面积分 | $\oint$ |
| 求和符号 | $\sum$ |
| 求积符号 | $\prod$ |
| 极限符号 | $lim$ |
| 对n开根号 | $\sqrt{n}$ |  
| 自然对数 | $\ln x$ |
| 常用对数 | $\lg x$ |
| 以a为底的对数 | $log_{a}{x}$ |
| 以e为底的指数 | $e^x$ |
| 大N | $\mathcal{N}$ |
| 上标 |  ${a}^{2}$  |
| 下标 |  ${a}_{2}$  |
| 向量 | $\vec{a}$ |
| 平均值 | $\overline{a}$ |
| 拟合值 |  $\widehat{a}$  |
| 一阶导数 |  $\dot{a}$  |
| 二阶导数 | $\ddot{a}$ |
| 模运算/向量加法 | $\oplus$ |
| 张量积/笛卡尔积 | $\otimes$ |
| 六角星(六芒星)上标 | $x^{\ast}$ |
| 五角星上标 | $x^{\star}$ |
| 方块 |  $\square$  |
| 黑填充方块 | $\blacksquare$ |
| 三角 |  $\triangle$  |
| 黑填充三角 | $\blacktriangle$ |
| 1度 | $1^\circ$ |
| 1分 |  $1^\prime$  |
| 1秒 | $1^{\prime\prime}$ |
| 左单箭头 | $\leftarrow$ |
| 右单箭头 | $\rightarrow$ |
| 左双箭头 | $\Leftarrow$ |
| 右双箭头 | $\Rightarrow$ |
| 左右单箭头 | $\leftrightarrow$ |
| 左右双箭头 | $\Leftrightarrow$ |
| ^帽子命令 | $\hat{a}$	 |
| ~帽子命令 | $\tilde{a}$	 |
| 倒尖帽子命令 | $\check{a}$ |
| 4声调帽子命令 | $\grave{a}$ |
| 2声调帽子命令 | $\acute{a}$ |
| 大^帽子命令 | $\widehat{abcdefg}$ |
| 大~帽子命令 | $\widetilde{abcdefg}$ |

**markdown(rmarkdown)中数学符号用`$`前后包裹**

## 数学表达式

```
|   类型   |          书写方式          |
|:---------:|:------------------------------------:|
| a 除以 b | $a \div b$ | 
| a 分之 b | $\frac{b}{a}$ |
| a 乘以 b | $a \times b$ |
| a 点乘 b | $a \cdot b$ |
| 二项式 | $\binom{n}{k}$ |
| 开n次方 | $\sqrt[n]{x}$ |
| 求和 | $\sum\limits_{i=0}^{10} i = 0 + 1 + 2 + \ldots + 10$ |
| 连乘 | $\prod\limits_{i=1}^5 i = 1 \times 2 \times 3 \times 4 \times 5$ |
| 积分 | $\int_{x=1}^{10} \frac{1}{x^2}$ |
| 二重积分 | $\iint\limits_{V} \mu(u,v)\,du\,dv$ |
| 三重积分 | $\iiint\limits_{V} \mu(u,v,w)\,du\,dv\,dw$ |
| 曲线曲面积分 | $\oint\limits_{V} f(s) \,ds$ |
| 微分 | $\frac{d}{dy} y^2$ |
| 极限 | $\lim\limits_{n \to \infty} \frac{1}{n}$ |
| 开方 | $\sqrt{\frac{a}{b+c}}(b+a)$ |
| 求余 | $\text{10 mod 3}$ |
```

|   类型   |    书写方式    |
|:---------:|:----------------:|
| a 除以 b | $a \div b$ |
| a 分之 b | $\frac{b}{a}$ |
| a 乘以 b | $a \times b$ |
| a 点乘 b | $a \cdot b$ |
| 二项式 | $\binom{n}{k}$ |
| 开n次方 | $\sqrt[n]{x}$ |
| 求和 | $\sum\limits_{i=0}^{10} i = 0 + 1 + 2 + \ldots + 10$ |
| 连乘 | $\prod\limits_{i=1}^5 i = 1 \times 2 \times 3 \times 4 \times 5$ |
| 积分 | $\int_{x=1}^{10} \frac{1}{x^2}$ |
| 二重积分 | $\iint\limits_{V} \mu(u,v)\,du\,dv$ |
| 三重积分 | $\iiint\limits_{V} \mu(u,v,w)\,du\,dv\,dw$ |
| 曲线曲面积分 | $\oint\limits_{V} f(s) \,ds$ |
| 微分 | $\frac{d}{dy} y^2$ |
| 极限 | $\lim\limits_{n \to \infty} \frac{1}{n}$ |
| 开方 | $\sqrt{\frac{a}{b+c}}(b+a)$ |
| 求余 | $\text{10 mod 3}$ |

**markdown(rmarkdown)中数学表达式用 `$$` 或者 `\[\]` 前后包裹,用 `$` 也可以但有上下标的符号此时渲染的不太美观**

*求和 $\sum$ 和求积 $\prod$ 等大型算符在行内公式出现时,上下标将显示在右边,
若要让上下标显示在上下方,可在算符命令后加上 `\limits` 命令*

如:
```
$\lim_{1 \to 10} x$
```

$\lim_{1 \to 10} x$

```
$\lim\limits_{1 \to 10} x$
```

$\lim\limits_{1 \to 10} x$

```
$\min\limits_j x$
```

$\min\limits_j x$

*公式内部中文用 `\mbox` 包括起来*,如:

```
$P\{\mbox{拒绝} \mid H_{0} \mbox{为真}\} = \alpha$
```

$P\{\mbox{拒绝} \mid H_{0} \mbox{为真}\} = \alpha$

## 矩阵与方程

一个矩阵典型的例子如下:

```
$$\begin{matrix}
1 & 2 & 3 \\
a & b & c
\end{matrix}$$
```

$$\begin{matrix}
1 & 2 & 3 \\
a & b & c
\end{matrix}$$

在`markdown`中渲染矩阵同数学公式一样由`\[\]`或者`$$`包裹,区别在于:

- 表示矩阵时要有起始标记 `\begin{matrix}` ,结束标记 `\end{matrix}`

- 每一行末尾标记 `\\` ，行间元素之间用 `&` 分隔

*起始标记和结束标记使用`matrix`时,渲染出的矩阵没有边框线,下面展示一下有边框线的*

```
|  标记使用类型  | 边框样式 |         书写方式          |
|:-------:|:------:|:------------------------------------:|
|matrix|无边框|$$\begin{matrix}
                    0&1&1\\
                    1&1&0\\
                    1&0&1\\
                 \end{matrix}$$|
|pmatrix|小括号边框|$$\begin{pmatrix}
                         0&1&1\\
                         1&1&0\\
                         1&0&1\\
                      \end{pmatrix}$$|
|bmatrix|中括号边框|$$\begin{bmatrix}
                         0&1&1\\
                         1&1&0\\
                         1&0&1\\
                      \end{bmatrix}$$|
|Bmatrix|大括号边框|$$\begin{Bmatrix}
                         0&1&1\\
                         1&1&0\\
                         1&0&1\\
                      \end{Bmatrix}$$|
|vmatrix|单竖线边框|$$\begin{vmatrix}
                         0&1&1\\
                         1&1&0\\
                         1&0&1\\
                      \end{vmatrix}$$|
|Vmatrix|双竖线边框|$$\begin{Vmatrix}
                         0&1&1\\
                         1&1&0\\
                         1&0&1\\
                      \end{Vmatrix}$$|
|smallmatrix|行内矩阵|$$\begin{smallmatrix}
                           0&1&1\\
                           1&1&0\\
                           1&0&1\\
                        \end{smallmatrix}$$|
```

|  标记使用类型  | 边框样式 |         书写方式          |
|:-------:|:------:|:------------------------------------:|
|matrix|无边框|$$\begin{matrix}
                    0&1&1\\
                    1&1&0\\
                    1&0&1\\
                 \end{matrix}$$|
|pmatrix|小括号边框|$$\begin{pmatrix}
                         0&1&1\\
                         1&1&0\\
                         1&0&1\\
                      \end{pmatrix}$$|
|bmatrix|中括号边框|$$\begin{bmatrix}
                         0&1&1\\
                         1&1&0\\
                         1&0&1\\
                      \end{bmatrix}$$|
|Bmatrix|大括号边框|$$\begin{Bmatrix}
                         0&1&1\\
                         1&1&0\\
                         1&0&1\\
                      \end{Bmatrix}$$|
|vmatrix|单竖线边框|$$\begin{vmatrix}
                         0&1&1\\
                         1&1&0\\
                         1&0&1\\
                      \end{vmatrix}$$|
|Vmatrix|双竖线边框|$$\begin{Vmatrix}
                         0&1&1\\
                         1&1&0\\
                         1&0&1\\
                      \end{Vmatrix}$$|
|smallmatrix|行内矩阵|$$\begin{smallmatrix}
                           0&1&1\\
                           1&1&0\\
                           1&0&1\\
                        \end{smallmatrix}$$|

线性代数中抽象矩阵经常会使用简略符号省略元素的表达,主要有三种:

- 横省略号: `\cdots` $\cdots$
- 竖省略号: `\vdots` $\vdots$
- 斜省略号: `\ddots` $\ddots$

比如下面这个例子:
```
$$\begin{bmatrix}
{a_{11}}&{a_{12}}&{\cdots}&{a_{1n}}\\
{a_{21}}&{a_{22}}&{\cdots}&{a_{2n}}\\
{\vdots}&{\vdots}&{\ddots}&{\vdots}\\
{a_{m1}}&{a_{m2}}&{\cdots}&{a_{mn}}\\
\end{bmatrix}$$
```

$$\begin{bmatrix}
{a_{11}}&{a_{12}}&{\cdots}&{a_{1n}}\\
{a_{21}}&{a_{22}}&{\cdots}&{a_{2n}}\\
{\vdots}&{\vdots}&{\ddots}&{\vdots}\\
{a_{m1}}&{a_{m2}}&{\cdots}&{a_{mn}}\\
\end{bmatrix}$$

方程组通常和矩阵联系起来,而方程组相较于矩阵最大的不同是方程组使用`cases`标记,

```
$$\begin{cases}
a_1x+b_1y+c_1z=d_1\\
a_2x+b_2y+c_2z=d_2\\
a_3x+b_3y+c_3z=d_3\\
\end{cases}$$
```

上面是一种比较简化的写法,标准版本应该这样写:
```
$$\begin{cases}
a_{1}x+b_{1}y+c_{1}z=d_{1}\\
a_{2}x+b_{2}y+c_{2}z=d_{2}\\
a_{3}x+b_{3}y+c_{3}z=d_{3}\\
\end{cases}$$
```
结果是一样的:

$$\begin{cases}
a_{1}x+b_{1}y+c_{1}z=d_{1}\\
a_{2}x+b_{2}y+c_{2}z=d_{2}\\
a_{3}x+b_{3}y+c_{3}z=d_{3}\\
\end{cases}$$

## 公式排版

### 多行展示长公式 `multline*`标识

```
$$\begin{multline*}
  f(x) = 5x^6 + 6x^5y - 520x^4y^2 + 1314x^3y^3 \\ 
  - 3x^2y^4 - 12 xy^5 + y^6 - a^3b^3c^3d^3 + 031213
  \end{multline*}$$
```

$$\begin{multline*}
  f(x) = 5x^6 + 6x^5y - 520x^4y^2 + 1314x^3y^3 \\ 
  - 3x^2y^4 - 12 xy^5 + y^6 - a^3b^3c^3d^3 + 031213
  \end{multline*}$$

### 拆分、对齐方程 `align*`标识

```
$$\begin{align*}
x&=y & w &=z & a&=b+c \\
2x&=-y & 3w&=\frac{1}{2}z & a&=b \\
-4+5x&=2+y & w+2&=-1+w & ab&=cb
  \end{align*}$$
```

$$\begin{align*}
x&=y & w &=z & a&=b+c \\
2x&=-y & 3w&=\frac{1}{2}z & a&=b \\
-4+5x&=2+y & w+2&=-1+w & ab&=cb
  \end{align*}$$

### 居中显示方程(不以等号对齐) `gather*`标识

```
$$\begin{gather*}
2x - 5y = 8 \\
3x^2 + 9y = 3a + c
  \end{gather*}$$
```

$$\begin{gather*}
2x - 5y = 8 \\
3x^2 + 9y = 3a + c
  \end{gather*}$$

### 多公式带标签排版
```
$$\begin{gather*}
x + y = z \tag{1} \\
a^2 + b^2 = c^2 \tag{2}
\end{gather*}$$
```

$$\begin{gather*}
x + y = z \tag{1} \\
a^2 + b^2 = c^2 \tag{2}
\end{gather*}$$

或者使用$\LaTeX$中的`equation`和`subequations`命令

*注意由于`equation`和`subequations`命令使用了$\LaTeX$中的`amsmath`包,在导出tex文件之外的设置中这两个命令可能无效*

```
$$
\begin{subequations} \label{subeqnexample}
\begin{equation}
\varepsilon \rho w_{tt}(s,t) = N[w_{s}(s,t),w_{st}(s,t)]_{s},
\label{subeqnparta}
\end{equation}
\begin{equation}
w_{tt}(1,t)+N[w_{s}(1,t),w_{st}(1,t)] = 0, \label{subeqnpartb}
\end{equation}
\end{subequations}
$$
```

### 数学公式中的括号问题

##### 小括号:

- 小括号可以直接使用`(`和`)`生成 :

```
$$f(x) = 3x^2 + (\frac{1}{x} + x) - 5$$
```

$$f(x) = 3x^2 + (\frac{1}{x} + x) - 5$$

- 使用`\left(`和`\right)`可以根据内容自动调整小括号大小

```
$$f(x) = 3x^2 + \left(\frac{1}{x} + x\right) - 5$$
```

$$f(x) = 3x^2 + \left(\frac{1}{x} + x\right) - 5$$

##### 中括号:

- 中括号可以直接使用`[`和`]`生成 :

```
$$ f(x) = [x - 1] $$
```

$$ f(x) = [x - 1]$$

- 中括号也可以使用`\lbrack`和`\rbrack`生成 :

```
$$f(x) = \lbrack x - 1 \rbrack$$
```

$$f(x) = \lbrack x - 1 \rbrack$$

- 使用`\left[`和`\right]`可以根据内容自动调整中括号大小

##### 大括号:

- 大括号可以使用`\{`和`\}`生成 :
> 注意在`LaTex`中,`{`和`}`有特殊含义，生成大括号时需要转义`{`和`}`

```
$$\{ x \}$$
```

$$\{ x \}$$

- 大括号也可以使用`\lbrace`和`\rbrace`生成 :

```
$$\lbrace x\rbrace$$
```

$$\lbrace x\rbrace$$

##### 尖括号:

尖括号可以使用`\langle`和`\rangle`生成 :

```
$$\langle x + y \rangle$$
```

$$\langle x + y \rangle$$

##### 组括号:

组括号可以使用`\lgroup`和`\rgroup`生成 :

```
$$ \lgroup x \rgroup $$
```

$$ \lgroup x \rgroup $$

##### 上下取整括号:

上下取整括号由`\lceil`,`\rceil`,`\lfloor`,`\rfloor`组合而成 :

- 向上取整由`\lceil`和`\rceil`生成

- 向下取整由`\lfloor`和`\rfloor`生成

```
$$ \lceil x \rceil $$
```

$$ \lceil x \rceil $$

##### 条件括号:

- `\lvert` 和 `\rvert` 左/右条件符号 (单条线)

- `\lVert` 和 `\rVert` 左/右双条线

```
$$ \lvert x + 1 \rvert $$
```

$$ \lvert x + 1 \rvert $$

```
$$ \lVert x + 1 \rVert $$
```

$$ \lVert x + 1 \rVert $$

## 练习 

exercise 1 

```{tex echo = FALSE}
$$
G_i^* = \frac{\sum\limits_{j = 1}^{m} \chi_j w_{i,j} - \overline{X} \sum\limits_{j=1}^{m} w_{i,j}}{S \times \sqrt{\left[{m \sum\limits_{j=1}^m w_{i,j}^2 - (\sum\limits_{j = 1}^{m} w_{i,j})^2 }\right] / (m - 1)}}
$$
```

$$
G_i^* = \frac{\sum\limits_{j = 1}^{m} \chi_j w_{i,j} - \overline{X} \sum\limits_{j=1}^{m} w_{i,j}}{S \times \sqrt{\left[{m \sum\limits_{j=1}^m w_{i,j}^2 - (\sum\limits_{j = 1}^{m} w_{i,j})^2 }\right] / (m - 1)}}
$$

exercise 2 

```{tex echo = FALSE}
$$
C = \sqrt{\left[{1 - \frac{\sum\limits_{i>j,j=2}^n \lvert{U_i - U_j}\rvert}{\sum\limits_{m=1}^{n-1} m}}\right] \times (\prod\limits_{i=1}^{n-1} U_i)^{\frac{1}{n-1}}}
$$
```

$$
C = \sqrt{\left[{1 - \frac{\sum\limits_{i>j,j=2}^n \lvert{U_i - U_j}\rvert}{\sum\limits_{m=1}^{n-1} m}}\right] \times (\prod\limits_{i=1}^{n-1} U_i)^{\frac{1}{n-1}}}
$$
